[package]
name = "reqwest-cross"
version = "0.1.0"
edition = "2021"
categories = ["network-programming", "wasm", "web-programming"]
keywords = ["http", "wasm", "native", "web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.16", default-features = false }
tokio = { version = "1.27.0", default-features = false, features = ["full"] }
# TODO 2: Stop pulling in all tokio features and put it behind a feature flag

# For compiling to web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
