[package]
name = "reqwest-cross"
version = "0.2.4"
description = "Wrapper around reqwest for use in both native and wasm"
keywords = ["http", "wasm", "native", "web", "request"]
repository = "https://github.com/c-git/reqwest-cross"
documentation = "https://docs.rs/reqwest-cross"
categories = ["web-programming::http-client", "wasm"]
authors = ["One <one.bgz1@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.16", default-features = false }

# For native compilation
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, optional = true }

# For compiling to wasm:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.34"

[dev-dependencies]
futures = "0.3.28"
tokio = { version = "1.27.0", default-features = false, features = ["macros"] }
wasm-bindgen-test = "0.3.34"

[features]
default = ["native-tokio"]
native-tokio = ["dep:tokio"]
