[package]
name = "reqwest-cross"
version = "0.1.0"
edition = "2021"
categories = ["network-programming", "wasm", "web-programming"]
keywords = ["http", "wasm", "native", "web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.16", default-features = false }

# For native compilation
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.27.0", default-features = false, optional = true }

# For compiling to wasm:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.34"

[dev-dependencies]
tokio = { version = "1.27.0", default-features = false, features = ["macros"] }
wasm-bindgen-test = "0.3.34"

[features]
native-tokio = ["dep:tokio"]
