name: Security audit
on:
  schedule:
    - cron: '00 10 * * 3' # 06:00 GMT-4
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@v3
      - uses: wykies/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories