name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  pull_request: 
    branches:
      - main
      - develop
      
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test WASM
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run tests
        run: wasm-pack test --headless --chrome

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          components: clippy
      - name: Linting
        run: cargo clippy --target="wasm32-unknown-unknown" -- -D warnings