name: Rust WASM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_in_browser:
    name: Test WASM in browser
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run tests
        run: wasm-pack test --headless --chrome

  clippy_wasm:
    name: Clippy WASM
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
          components: clippy
      - name: Linting
        run: cargo clippy --target="wasm32-unknown-unknown" -- -D warnings

  trunk_build:
    name: trunk build
    runs-on: ubuntu-latest
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: ./trunk build
